// Script to initialize Supabase database tables
const supabase = require('./db/supabase');

async function initializeDatabase() {
  console.log('Initializing Supabase database tables...');

  try {
    // Create users table
    const { error: userError } = await supabase.rpc('create_extension', { name: 'pg_uuid_ext' });
    if (userError && userError.message !== 'extension "pg_uuid_ext" does not exist') {
      console.log('UUID extension handling:', userError?.message || 'Extension setup handled');
    }

    // Note: In Supabase, tables are typically created via the dashboard or migrations
    // For this example, we'll assume tables have been created with the following structure:
    /*
    CREATE TABLE users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      wallet_address TEXT UNIQUE NOT NULL,
      username TEXT,
      email TEXT,
      name TEXT,
      avatar_url TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE TABLE shows (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT REFERENCES users(id),
      title TEXT NOT NULL,
      description TEXT,
      category TEXT,
      thumbnail_url TEXT,
      stream_url TEXT,
      is_live BOOLEAN DEFAULT FALSE,
      viewers INTEGER DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE TABLE streams (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      show_id BIGINT REFERENCES shows(id),
      streamer_id BIGINT REFERENCES users(id),
      stream_key TEXT,
      is_active BOOLEAN DEFAULT FALSE,
      viewers INTEGER DEFAULT 0,
      started_at TIMESTAMP WITH TIME ZONE,
      ended_at TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE TABLE tips (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      from_user_id BIGINT REFERENCES users(id),
      to_user_id BIGINT REFERENCES users(id),
      amount DECIMAL(10, 2) NOT NULL,
      currency TEXT DEFAULT 'ETH',
      message TEXT,
      transaction_hash TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    */

    console.log('Database initialization script completed.');
    console.log('Note: In Supabase, tables are typically created via the dashboard or through SQL editor.');
    console.log('Please make sure the required tables are created in your Supabase project.');
  } catch (error) {
    console.error('Error during database initialization:', error.message);
  }
}

initializeDatabase();